defaults: &defaults
  access_key_id: "AKIAISQWLDVKDQMHCU3Q"
  secret_access_key: "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"
development:
  <<: *defaults
  bucket: "waterdesigndev"
test:
  <<: *defaults
  bucket: "waterdesign.ca.test"
production:
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  bucket: "waterdesign"